name: Deploy to PROD

on:
  workflow_dispatch:
  push:
    branches: [ main ]


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
        
    
    - name: Merge main -> PROD
      uses: devmasx/merge-branch@master
      with:
        type: now
        from_branch: main
        target_branch: PROD
        github_token: ${{ secrets.GIT_TOKEN }}
